---
title: Oslo Perl Mongers
description: Check out Oslo.pm for news about Perl in Oslo/Norway
logo: /images/oslo.pm-logo.png
author: Oslo.pm board members
facebook:
  publisher: groups/oslo.pm
social:
  name: Oslo.pm
  links:
  - https://www.facebook.com/groups/oslo.pm
  - https://www.meetup.com/Oslo-pm

maps_url: "https://maps.google.com/maps?f=q&hl=en&amp;q="
event_date_format: "%Y-%m-%d %H:%M"

paginate: 10
paginate_path: "/news/all/page:num"

permalink: /:year/:month/:day/:title.html
destination: ./_site
plugins:
- jekyll-feed
- jekyll-redirect-from
- jekyll-relative-links
- jekyll-paginate
- jekyll-seo-tag
- jekyll-titles-from-headings
